import { Level, WorkingType } from "@/types/enum";

export const recruiters: Recruiter[] = [
  {
    userId: 1,
    email: "contact@techcorp.vn",
    name: "TechCorp Vietnam",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description: "Leading tech company in Southeast Asia",
    website: "https://techcorp.vn",
    createdAt: new Date().toISOString(),
    createdBy: "admin",
    jobs: Array(12).fill(null),
  },
  {
    userId: 2,
    email: "contact@startupxyz.com",
    name: "StartupXYZ",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description: "Innovative SaaS solutions for businesses",
    website: "https://startupxyz.com",
    createdAt: new Date().toISOString(),
    createdBy: "admin",
    jobs: Array(8).fill(null),
  },
  {
    userId: 3,
    email: "contact@designstudio.vn",
    name: "DesignStudio",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description: "Creative design agency with global clients",
    website: "https://designstudio.vn",
    createdAt: new Date().toISOString(),
    createdBy: "admin",
    jobs: Array(5).fill(null),
  },
];

export const blogs: Blog[] = [
  {
    blogId: 1,
    title: "5 Kỹ Năng Cần Thiết Cho Lập Trình Viên Trong 2025",
    description:
      "Khám phá những kỹ năng quan trọng nhất mà mỗi lập trình viên cần có...",
    banner:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    tags: ["Career Tips", "Programming"],
    draft: false,
    activity: {
      totalLikes: 150,
      totalReads: 1200,
      totalParentComments: 25,
      totalReplies: 48,
    },
    createdAt: "2025-10-15T00:00:00Z",
    createdBy: "admin",
  },
  {
    blogId: 2,
    title: "Cách Chuẩn Bị Cho Phỏng Vấn Kỹ Thuật",
    description:
      "Hướng dẫn chi tiết để giúp bạn thành công trong phỏng vấn kỹ thuật...",
    banner:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    tags: ["Interview Tips", "Career"],
    draft: false,
    activity: {
      totalLikes: 200,
      totalReads: 1500,
      totalParentComments: 30,
      totalReplies: 55,
    },
    createdAt: "2025-10-10T00:00:00Z",
    createdBy: "admin",
  },
  {
    blogId: 3,
    title: "Xu Hướng Công Nghệ Năm 2025",
    description:
      "Những công nghệ mới sẽ thay đổi ngành công nghiệp trong năm tới...",
    banner:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    tags: ["Technology", "Trends"],
    draft: false,
    activity: {
      totalLikes: 180,
      totalReads: 1350,
      totalParentComments: 28,
      totalReplies: 52,
    },
    createdAt: "2025-10-05T00:00:00Z",
    createdBy: "admin",
  },
];

export const allJobs: Job[] = [
  {
    jobId: 1,
    title: "Senior Frontend Engineer",
    description:
      "Looking for an experienced frontend engineer to join our growing team. You will work on building scalable web applications using modern technologies.",
    startDate: "2025-02-01",
    endDate: "2025-12-31",
    active: true,
    level: Level.SENIOR,
    quantity: 2,
    salary: 3000,
    workingType: WorkingType.FULL_TIME,
    location: "Ho Chi Minh City",
    createdAt: "2025-01-15T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: 1,
        name: "React",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: 2,
        name: "TypeScript",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: 3,
        name: "Tailwind CSS",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
  },
  {
    jobId: 2,
    title: "Product Manager",
    description:
      "Join our product team and shape the future of our platform. Lead product strategy and work with cross-functional teams.",
    startDate: "2025-02-15",
    endDate: "2025-12-31",
    active: true,
    level: Level.MIDDLE,
    quantity: 1,
    salary: 2500,
    workingType: WorkingType.FULL_TIME,
    location: "Hanoi",
    createdAt: "2025-01-14T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: 4,
        name: "Product Strategy",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: 5,
        name: "Analytics",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
  },
  {
    jobId: 3,
    title: "UX/UI Designer",
    description:
      "Create beautiful and intuitive user experiences for our clients. Work on diverse projects across web and mobile platforms.",
    startDate: "2025-02-01",
    endDate: "2025-12-31",
    active: true,
    level: Level.JUNIOR,
    quantity: 1,
    salary: 2000,
    workingType: WorkingType.FULL_TIME,
    location: "Da Nang",
    createdAt: "2025-01-13T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: 6,
        name: "Figma",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: 7,
        name: "UI Design",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: 8,
        name: "Prototyping",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
  },
  {
    jobId: 4,
    title: "Backend Engineer (Node.js)",
    description:
      "Build scalable backend systems with Node.js and AWS. Work on microservices architecture and cloud infrastructure.",
    startDate: "2025-02-10",
    endDate: "2025-12-31",
    active: true,
    level: Level.SENIOR,
    quantity: 2,
    salary: 3200,
    workingType: WorkingType.FULL_TIME,
    location: "Ho Chi Minh City",
    createdAt: "2025-01-12T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: 9,
        name: "Node.js",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: 10,
        name: "AWS",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: 11,
        name: "PostgreSQL",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
  },
  {
    jobId: 5,
    title: "Data Analyst",
    description:
      "Analyze and visualize data to drive business insights. Work with large datasets and create actionable reports.",
    startDate: "2025-03-01",
    endDate: "2025-12-31",
    active: true,
    level: Level.MIDDLE,
    quantity: 1,
    salary: 2200,
    workingType: WorkingType.FULL_TIME,
    location: "Hanoi",
    createdAt: "2025-01-10T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: 12,
        name: "Python",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: 13,
        name: "SQL",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: 14,
        name: "Tableau",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
  },
  {
    jobId: 6,
    title: "Mobile App Developer",
    description:
      "Develop iOS and Android applications for mobile-first experiences. Build cross-platform apps using Flutter or React Native.",
    startDate: "2025-02-20",
    endDate: "2025-12-31",
    active: true,
    level: Level.MIDDLE,
    quantity: 2,
    salary: 2400,
    workingType: WorkingType.FULL_TIME,
    location: "Da Nang",
    createdAt: "2025-01-08T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: 15,
        name: "Flutter",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: 16,
        name: "React Native",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: 17,
        name: "Mobile UI",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
  },
  {
    jobId: 7,
    title: "DevOps Engineer",
    description:
      "Manage and optimize cloud infrastructure and deployments. Implement CI/CD pipelines and monitoring solutions.",
    startDate: "2025-02-15",
    endDate: "2025-12-31",
    active: true,
    level: Level.SENIOR,
    quantity: 1,
    salary: 3100,
    workingType: WorkingType.FULL_TIME,
    location: "Ho Chi Minh City",
    createdAt: "2025-01-05T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: 18,
        name: "Kubernetes",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: 19,
        name: "Docker",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: 10,
        name: "AWS",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
  },
  {
    jobId: 8,
    title: "QA Engineer",
    description:
      "Ensure product quality through comprehensive testing strategies. Develop automated tests and maintain test documentation.",
    startDate: "2025-03-01",
    endDate: "2025-12-31",
    active: true,
    level: Level.JUNIOR,
    quantity: 2,
    salary: 1800,
    workingType: WorkingType.FULL_TIME,
    location: "Hanoi",
    createdAt: "2025-01-03T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: 20,
        name: "Automation Testing",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: 21,
        name: "Selenium",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: 22,
        name: "Manual Testing",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
  },
  {
    jobId: 9,
    title: "Full Stack Developer Intern",
    description:
      "Learn and grow with our experienced team. Work on real projects using modern web technologies.",
    startDate: "2025-02-01",
    endDate: "2025-08-31",
    active: true,
    level: Level.INTERN,
    quantity: 3,
    salary: 500,
    workingType: WorkingType.PART_TIME,
    location: "Ho Chi Minh City",
    createdAt: "2025-01-01T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: 1,
        name: "React",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: 9,
        name: "Node.js",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
  },
  {
    jobId: 10,
    title: "Remote Content Writer",
    description:
      "Create engaging content for our blog and marketing materials. Work remotely from anywhere in Vietnam.",
    startDate: "2025-02-01",
    endDate: "2025-12-31",
    active: true,
    level: Level.FRESHER,
    quantity: 1,
    salary: 1200,
    workingType: WorkingType.ONLINE,
    location: "Remote",
    createdAt: "2025-01-01T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: 23,
        name: "Content Writing",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: 24,
        name: "SEO",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
  },
];
