import { Level, WorkingType } from "@/types/enum";
import {
  Application,
  Blog,
  Job,
  NotificationType,
  Recruiter,
  User,
} from "@/types/model";

export const recruiters: Recruiter[] = [
  {
    userId: "1",
    fullName: "TechCorp Vietnam",
    contact: {
      email: "contact@techcorp.vn",
      phone: "+84 28 1234 5678",
    },
    password: "password123",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description: "Leading tech company in Southeast Asia",
    website: "https://techcorp.vn",
    address: "123 Nguyen Hue, District 1, Ho Chi Minh City",
    createdAt: new Date().toISOString(),
    createdBy: "admin",
  },
  {
    userId: "2",
    fullName: "StartupXYZ",
    contact: {
      email: "contact@startupxyz.com",
      phone: "+84 24 1234 5678",
    },
    password: "password123",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description: "Innovative SaaS solutions for businesses",
    website: "https://startupxyz.com",
    address: "456 Tran Hung Dao, Hoan Kiem, Hanoi",
    createdAt: new Date().toISOString(),
    createdBy: "admin",
  },
  {
    userId: "3",
    fullName: "DesignStudio",
    contact: {
      email: "contact@designstudio.vn",
      phone: "+84 236 1234 567",
    },
    password: "password123",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description: "Creative design agency with global clients",
    website: "https://designstudio.vn",
    address: "789 Bach Dang, Hai Chau, Da Nang",
    createdAt: new Date().toISOString(),
    createdBy: "admin",
  },
];

export const blogs: Blog[] = [
  {
    blogId: "1",
    title: "5 Kỹ Năng Cần Thiết Cho Lập Trình Viên Trong 2025",
    description:
      "Khám phá những kỹ năng quan trọng nhất mà mỗi lập trình viên cần có...",
    banner:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    content: [],
    tags: ["Career Tips", "Programming"],
    draft: false,
    activity: {
      totalLikes: 150,
      totalReads: 1200,
      totalComments: 73,
      totalParentComments: 25,
    },
    createdAt: "2025-10-15T00:00:00Z",
    createdBy: "admin",
  },
  {
    blogId: "2",
    title: "Cách Chuẩn Bị Cho Phỏng Vấn Kỹ Thuật",
    description:
      "Hướng dẫn chi tiết để giúp bạn thành công trong phỏng vấn kỹ thuật...",
    banner:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    content: [],
    tags: ["Interview Tips", "Career"],
    draft: false,
    activity: {
      totalLikes: 200,
      totalReads: 1500,
      totalComments: 85,
      totalParentComments: 30,
    },
    createdAt: "2025-10-10T00:00:00Z",
    createdBy: "admin",
  },
  {
    blogId: "3",
    title: "Xu Hướng Công Nghệ Năm 2025",
    description:
      "Những công nghệ mới sẽ thay đổi ngành công nghiệp trong năm tới...",
    banner:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    content: [],
    tags: ["Technology", "Trends"],
    draft: false,
    activity: {
      totalLikes: 180,
      totalReads: 1350,
      totalComments: 80,
      totalParentComments: 28,
    },
    createdAt: "2025-10-05T00:00:00Z",
    createdBy: "admin",
  },
];

export const allBlogs: Blog[] = [
  {
    blogId: "1",
    title: "Hướng dẫn sử dụng Docker cho người mới",
    banner:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description: "Bài viết hướng dẫn cơ bản về Docker, container và image.",
    content: [
      "Docker là công cụ giúp đóng gói ứng dụng vào container.",
      "Bạn có thể chạy Docker trên Windows, macOS, hoặc Linux.",
    ],
    tags: ["DevOps", "Docker", "Tutorial"],
    draft: false,
    activity: {
      totalLikes: 125,
      totalReads: 3100,
      totalComments: 47,
      totalParentComments: 14,
    },
    createdAt: "2025-01-15T10:30:00Z",
    createdBy: "admin",
  },
  {
    blogId: "2",
    title: "React 18: Những điểm mới đáng chú ý",
    banner:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description:
      "Khám phá các tính năng mới của React 18 như concurrent rendering.",
    content: [
      "React 18 giới thiệu concurrent mode để tối ưu UI.",
      "useTransition giúp cải thiện trải nghiệm người dùng.",
    ],
    tags: ["React", "Frontend", "JavaScript"],
    draft: false,
    activity: {
      totalLikes: 203,
      totalReads: 4500,
      totalComments: 93,
      totalParentComments: 28,
    },
    createdAt: "2025-02-10T09:45:00Z",
    createdBy: "editor01",
  },
  {
    blogId: "3",
    title: "Top 5 IDE tốt nhất cho lập trình viên năm 2025",
    banner:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description: "Tổng hợp những IDE phổ biến nhất hiện nay.",
    content: [
      "Visual Studio Code",
      "IntelliJ IDEA",
      "PyCharm",
      "WebStorm",
      "Eclipse",
    ],
    tags: ["IDE", "Developer", "Tools"],
    draft: false,
    activity: {
      totalLikes: 88,
      totalReads: 2200,
      totalComments: 22,
      totalParentComments: 7,
    },
    createdAt: "2025-03-05T11:00:00Z",
    createdBy: "authorB",
  },
  {
    blogId: "4",
    title: "Sự khác biệt giữa SQL và NoSQL",
    banner:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description:
      "Bài viết phân tích ưu và nhược điểm của hai loại cơ sở dữ liệu.",
    content: [],
    tags: ["Database", "SQL", "NoSQL"],
    draft: false,
    activity: {
      totalLikes: 175,
      totalReads: 3800,
      totalComments: 60,
      totalParentComments: 20,
    },
    createdAt: "2025-03-20T14:00:00Z",
    createdBy: "admin",
  },
  {
    blogId: "5",
    title: "10 mẹo tăng hiệu suất làm việc với VS Code",
    banner:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description: "",
    content: [],
    tags: ["VSCode", "Productivity", "Tips"],
    draft: false,
    activity: {
      totalLikes: 145,
      totalReads: 2900,
      totalComments: 37,
      totalParentComments: 16,
    },
    createdAt: "2025-03-28T08:30:00Z",
    createdBy: "devtips",
  },
  {
    blogId: "6",
    title: "Giới thiệu về RESTful API và nguyên tắc thiết kế",
    banner:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description: "Hiểu rõ về REST và cách xây dựng API hiệu quả.",
    content: [],
    tags: ["API", "Backend", "REST"],
    draft: false,
    activity: {
      totalLikes: 167,
      totalReads: 3100,
      totalComments: 48,
      totalParentComments: 19,
    },
    createdAt: "2025-04-02T10:10:00Z",
    createdBy: "api_master",
  },
  {
    blogId: "7",
    title: "Cách deploy ứng dụng Node.js lên Vercel",
    banner:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description: "",
    content: [],
    tags: ["Node.js", "Deployment", "Vercel"],
    draft: false,
    activity: {
      totalLikes: 74,
      totalReads: 1600,
      totalComments: 19,
      totalParentComments: 8,
    },
    createdAt: "2025-04-05T12:00:00Z",
    createdBy: "editor01",
  },
  {
    blogId: "8",
    title: "So sánh TypeScript và JavaScript: Khi nào nên dùng?",
    banner:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description: "",
    content: [],
    tags: ["TypeScript", "JavaScript", "Programming"],
    draft: false,
    activity: {
      totalLikes: 210,
      totalReads: 4200,
      totalComments: 92,
      totalParentComments: 32,
    },
    createdAt: "2025-04-20T09:00:00Z",
    createdBy: "admin",
  },
  {
    blogId: "9",
    title: "Tổng quan về Git và GitHub cho người mới bắt đầu",
    banner:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description: "Cách sử dụng Git cơ bản và làm việc với GitHub.",
    content: [],
    tags: ["Git", "Version Control"],
    draft: false,
    activity: {
      totalLikes: 189,
      totalReads: 4000,
      totalComments: 67,
      totalParentComments: 25,
    },
    createdAt: "2025-05-01T10:00:00Z",
    createdBy: "authorC",
  },
  {
    blogId: "10",
    title: "Cách tạo blog cá nhân với Next.js và Markdown",
    banner:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description: "",
    content: [],
    tags: ["Next.js", "Markdown", "WebDev"],
    draft: false,
    activity: {
      totalLikes: 94,
      totalReads: 2000,
      totalComments: 23,
      totalParentComments: 10,
    },
    createdAt: "2025-05-15T11:30:00Z",
    createdBy: "frontenddev",
  },
  {
    blogId: "11",
    title: "Những xu hướng công nghệ năm 2025 bạn không nên bỏ lỡ",
    banner:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description: "",
    content: [],
    tags: ["Tech Trends", "AI", "Cloud", "Blockchain"],
    draft: false,
    activity: {
      totalLikes: 301,
      totalReads: 6100,
      totalComments: 132,
      totalParentComments: 40,
    },
    createdAt: "2025-06-01T08:00:00Z",
    createdBy: "techinsider",
  },
  {
    blogId: "12",
    title: "Tại sao nên học lập trình Python trong năm 2025?",
    banner:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    description: "",
    content: [],
    tags: ["Python", "Beginner", "Career"],
    draft: false,
    activity: {
      totalLikes: 250,
      totalReads: 5400,
      totalComments: 103,
      totalParentComments: 33,
    },
    createdAt: "2025-06-10T09:20:00Z",
    createdBy: "admin",
  },
];

export const allJobs: Job[] = [
  {
    jobId: "1",
    title: "Senior Frontend Engineer",
    description:
      "Looking for an experienced frontend engineer to join our growing team. You will work on building scalable web applications using modern technologies.",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-12-31"),
    active: true,
    level: Level.SENIOR,
    quantity: 2,
    salary: 3000,
    workingType: WorkingType.FULL_TIME,
    location: "Ho Chi Minh City",
    createdAt: "2025-01-15T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: "1",
        name: "React",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: "2",
        name: "TypeScript",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: "3",
        name: "Tailwind CSS",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
    career: {
      careerId: "1",
      name: "Software Development",
      createdAt: "2025-01-01T00:00:00Z",
      createdBy: "admin",
    },
  },
  {
    jobId: "2",
    title: "Product Manager",
    description:
      "Join our product team and shape the future of our platform. Lead product strategy and work with cross-functional teams.",
    startDate: new Date("2025-02-15"),
    endDate: new Date("2025-12-31"),
    active: true,
    level: Level.MIDDLE,
    quantity: 1,
    salary: 2500,
    workingType: WorkingType.FULL_TIME,
    location: "Hanoi",
    createdAt: "2025-01-14T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: "4",
        name: "Product Strategy",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: "5",
        name: "Analytics",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
    career: {
      careerId: "2",
      name: "Product Management",
      createdAt: "2025-01-01T00:00:00Z",
      createdBy: "admin",
    },
  },
  {
    jobId: "3",
    title: "UX/UI Designer",
    description:
      "Create beautiful and intuitive user experiences for our clients. Work on diverse projects across web and mobile platforms.",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-12-31"),
    active: true,
    level: Level.JUNIOR,
    quantity: 1,
    salary: 2000,
    workingType: WorkingType.FULL_TIME,
    location: "Da Nang",
    createdAt: "2025-01-13T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: "6",
        name: "Figma",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: "7",
        name: "UI Design",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: "8",
        name: "Prototyping",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
    career: {
      careerId: "3",
      name: "Design",
      createdAt: "2025-01-01T00:00:00Z",
      createdBy: "admin",
    },
  },
  {
    jobId: "4",
    title: "Backend Engineer (Node.js)",
    description:
      "Build scalable backend systems with Node.js and AWS. Work on microservices architecture and cloud infrastructure.",
    startDate: new Date("2025-02-10"),
    endDate: new Date("2025-12-31"),
    active: true,
    level: Level.SENIOR,
    quantity: 2,
    salary: 3200,
    workingType: WorkingType.FULL_TIME,
    location: "Ho Chi Minh City",
    createdAt: "2025-01-12T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: "9",
        name: "Node.js",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: "10",
        name: "AWS",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: "11",
        name: "PostgreSQL",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
    career: {
      careerId: "1",
      name: "Software Development",
      createdAt: "2025-01-01T00:00:00Z",
      createdBy: "admin",
    },
  },
  {
    jobId: "5",
    title: "Data Analyst",
    description:
      "Analyze and visualize data to drive business insights. Work with large datasets and create actionable reports.",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-12-31"),
    active: true,
    level: Level.MIDDLE,
    quantity: 1,
    salary: 2200,
    workingType: WorkingType.FULL_TIME,
    location: "Hanoi",
    createdAt: "2025-01-10T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: "12",
        name: "Python",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: "13",
        name: "SQL",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: "14",
        name: "Tableau",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
    career: {
      careerId: "4",
      name: "Data Science",
      createdAt: "2025-01-01T00:00:00Z",
      createdBy: "admin",
    },
  },
  {
    jobId: "6",
    title: "Mobile App Developer",
    description:
      "Develop iOS and Android applications for mobile-first experiences. Build cross-platform apps using Flutter or React Native.",
    startDate: new Date("2025-02-20"),
    endDate: new Date("2025-12-31"),
    active: true,
    level: Level.MIDDLE,
    quantity: 2,
    salary: 2400,
    workingType: WorkingType.FULL_TIME,
    location: "Da Nang",
    createdAt: "2025-01-08T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: "15",
        name: "Flutter",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: "16",
        name: "React Native",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: "17",
        name: "Mobile UI",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
    career: {
      careerId: "1",
      name: "Software Development",
      createdAt: "2025-01-01T00:00:00Z",
      createdBy: "admin",
    },
  },
  {
    jobId: "7",
    title: "DevOps Engineer",
    description:
      "Manage and optimize cloud infrastructure and deployments. Implement CI/CD pipelines and monitoring solutions.",
    startDate: new Date("2025-02-15"),
    endDate: new Date("2025-12-31"),
    active: true,
    level: Level.SENIOR,
    quantity: 1,
    salary: 3100,
    workingType: WorkingType.FULL_TIME,
    location: "Ho Chi Minh City",
    createdAt: "2025-01-05T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: "18",
        name: "Kubernetes",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: "19",
        name: "Docker",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: "10",
        name: "AWS",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
    career: {
      careerId: "5",
      name: "DevOps",
      createdAt: "2025-01-01T00:00:00Z",
      createdBy: "admin",
    },
  },
  {
    jobId: "8",
    title: "QA Engineer",
    description:
      "Ensure product quality through comprehensive testing strategies. Develop automated tests and maintain test documentation.",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-12-31"),
    active: true,
    level: Level.JUNIOR,
    quantity: 2,
    salary: 1800,
    workingType: WorkingType.FULL_TIME,
    location: "Hanoi",
    createdAt: "2025-01-03T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: "20",
        name: "Automation Testing",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: "21",
        name: "Selenium",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: "22",
        name: "Manual Testing",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
    career: {
      careerId: "6",
      name: "Quality Assurance",
      createdAt: "2025-01-01T00:00:00Z",
      createdBy: "admin",
    },
  },
  {
    jobId: "9",
    title: "Full Stack Developer Intern",
    description:
      "Learn and grow with our experienced team. Work on real projects using modern web technologies.",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-08-31"),
    active: true,
    level: Level.INTERN,
    quantity: 3,
    salary: 500,
    workingType: WorkingType.PART_TIME,
    location: "Ho Chi Minh City",
    createdAt: "2025-01-01T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: "1",
        name: "React",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: "9",
        name: "Node.js",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
    career: {
      careerId: "1",
      name: "Software Development",
      createdAt: "2025-01-01T00:00:00Z",
      createdBy: "admin",
    },
  },
  {
    jobId: "10",
    title: "Remote Content Writer",
    description:
      "Create engaging content for our blog and marketing materials. Work remotely from anywhere in Vietnam.",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-12-31"),
    active: true,
    level: Level.FRESHER,
    quantity: 1,
    salary: 1200,
    workingType: WorkingType.ONLINE,
    location: "Remote",
    createdAt: "2025-01-01T00:00:00Z",
    createdBy: "admin",
    skills: [
      {
        skillId: "23",
        name: "Content Writing",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
      {
        skillId: "24",
        name: "SEO",
        createdAt: "2025-01-01T00:00:00Z",
        createdBy: "admin",
      },
    ],
    career: {
      careerId: "7",
      name: "Marketing",
      createdAt: "2025-01-01T00:00:00Z",
      createdBy: "admin",
    },
  },
];

export const allRecruiter: Recruiter[] = [
  {
    userId: "1",
    fullName: "TechCorp Vietnam",
    contact: {
      email: "contact@techcorp.vn",
      phone: "+84 28 1234 5678",
    },
    password: "password123",
    address: "123 Nguyen Hue, District 1, Ho Chi Minh City",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=80",
    description:
      "Leading software development company with 10+ years of experience in creating innovative solutions.",
    website: "https://techcorp.vn",
    createdAt: "2023-01-15T00:00:00Z",
    createdBy: "admin",
  },
  {
    userId: "2",
    fullName: "StartupXYZ",
    contact: {
      email: "contact@startupxyz.io",
      phone: "+84 24 1234 5678",
    },
    password: "password123",
    address: "456 Tran Hung Dao, Hoan Kiem, Hanoi",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=80",
    description:
      "Fast-growing startup focused on AI and machine learning solutions for businesses.",
    website: "https://startupxyz.io",
    createdAt: "2023-02-20T00:00:00Z",
    createdBy: "admin",
  },
  {
    userId: "3",
    fullName: "DesignStudio",
    contact: {
      email: "contact@designstudio.vn",
      phone: "+84 236 1234 567",
    },
    password: "password123",
    address: "789 Bach Dang, Hai Chau, Da Nang",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=80",
    description:
      "Creative agency specializing in UI/UX design and brand development.",
    website: "https://designstudio.vn",
    createdAt: "2023-03-10T00:00:00Z",
    createdBy: "admin",
  },
  {
    userId: "4",
    fullName: "CloudServices Inc",
    contact: {
      email: "contact@cloudservices.io",
      phone: "+84 28 2234 5678",
    },
    password: "password123",
    address: "321 Le Loi, District 3, Ho Chi Minh City",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=80",
    description:
      "Enterprise cloud infrastructure and services provider for businesses worldwide.",
    website: "https://cloudservices.io",
    createdAt: "2023-04-05T00:00:00Z",
    createdBy: "admin",
  },
  {
    userId: "5",
    fullName: "DataCorp",
    contact: {
      email: "contact@datacorp.vn",
      phone: "+84 24 3234 5678",
    },
    password: "password123",
    address: "654 Ba Trieu, Dong Da, Hanoi",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=80",
    description:
      "Data analytics company helping businesses make data-driven decisions.",
    website: "https://datacorp.vn",
    createdAt: "2023-05-12T00:00:00Z",
    createdBy: "admin",
  },
  {
    userId: "6",
    fullName: "AppStudio",
    contact: {
      email: "contact@appstudio.vn",
      phone: "+84 236 2234 567",
    },
    password: "password123",
    address: "987 Nguyen Van Linh, Thanh Khe, Da Nang",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=80",
    description:
      "Mobile app development studio creating innovative applications for iOS and Android.",
    website: "https://appstudio.vn",
    createdAt: "2023-06-18T00:00:00Z",
    createdBy: "admin",
  },
  {
    userId: "7",
    fullName: "InfraTech",
    contact: {
      email: "contact@infratech.io",
      phone: "+84 28 3234 5678",
    },
    password: "password123",
    address: "147 Vo Van Tan, District 3, Ho Chi Minh City",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=80",
    description:
      "Infrastructure and DevOps solutions provider for cloud-native applications.",
    website: "https://infratech.io",
    createdAt: "2023-07-22T00:00:00Z",
    createdBy: "admin",
  },
  {
    userId: "8",
    fullName: "GameStudio",
    contact: {
      email: "contact@gamestudio.vn",
      phone: "+84 24 4234 5678",
    },
    password: "password123",
    address: "258 Cau Giay, Cau Giay, Hanoi",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=80",
    description:
      "Game development studio creating engaging mobile and PC games.",
    website: "https://gamestudio.vn",
    createdAt: "2023-08-30T00:00:00Z",
    createdBy: "admin",
  },
];

export const notifications: NotificationType[] = [
  {
    notificationId: "n1",
    type: "LIKE_BLOG",
    seen: false,
    blog: { blogId: "b101" },
    actor: { userId: "u201" },
    recipient: { userId: "u001" },
    createdAt: "2025-11-01T08:30:00Z",
  },
  {
    notificationId: "n2",
    type: "COMMENT_BLOG",
    seen: false,
    blog: { blogId: "b102" },
    actor: { userId: "u202" },
    recipient: { userId: "u002" },
    comment: { commentId: "c301" },
    createdAt: "2025-11-01T09:00:00Z",
  },
  {
    notificationId: "n3",
    type: "REPLY_COMMENT",
    seen: true,
    blog: { blogId: "b103" },
    actor: { userId: "u203" },
    recipient: { userId: "u003" },
    reply: { commentId: "c302" },
    repliedOnComment: { commentId: "c301" },
    createdAt: "2025-11-01T09:15:00Z",
  },
  {
    notificationId: "n4",
    type: "FOLLOW_USER",
    seen: false,
    blog: { blogId: "b104" },
    actor: { userId: "u204" },
    recipient: { userId: "u004" },
    createdAt: "2025-11-01T10:00:00Z",
  },
  {
    notificationId: "n5",
    type: "MENTION_COMMENT",
    seen: true,
    blog: { blogId: "b105" },
    actor: { userId: "u205" },
    recipient: { userId: "u005" },
    comment: { commentId: "c303" },
    createdAt: "2025-11-01T10:30:00Z",
  },
  {
    notificationId: "n6",
    type: "MENTION_REPLY",
    seen: false,
    blog: { blogId: "b106" },
    actor: { userId: "u206" },
    recipient: { userId: "u006" },
    reply: { commentId: "c304" },
    createdAt: "2025-11-01T11:00:00Z",
  },
  {
    notificationId: "n7",
    type: "BLOG_FEATURED",
    seen: false,
    blog: { blogId: "b107" },
    actor: { userId: "u207" },
    recipient: { userId: "u007" },
    createdAt: "2025-11-01T12:00:00Z",
  },
  {
    notificationId: "n8",
    type: "COMMENT_LIKED",
    seen: true,
    blog: { blogId: "b108" },
    actor: { userId: "u208" },
    recipient: { userId: "u008" },
    comment: { commentId: "c305" },
    createdAt: "2025-11-01T12:30:00Z",
  },
  {
    notificationId: "n9",
    type: "REPLY_LIKED",
    seen: false,
    blog: { blogId: "b109" },
    actor: { userId: "u209" },
    recipient: { userId: "u009" },
    reply: { commentId: "c306" },
    createdAt: "2025-11-01T13:00:00Z",
  },
  {
    notificationId: "n10",
    type: "BLOG_SHARED",
    seen: true,
    blog: { blogId: "b110" },
    actor: { userId: "u210" },
    recipient: { userId: "u010" },
    createdAt: "2025-11-01T14:00:00Z",
  },
  {
    notificationId: "n11",
    type: "COMMENT_REPORTED",
    seen: false,
    blog: { blogId: "b111" },
    actor: { userId: "u211" },
    recipient: { userId: "u011" },
    comment: { commentId: "c307" },
    createdAt: "2025-11-01T15:00:00Z",
  },
  {
    notificationId: "n12",
    type: "SYSTEM_ANNOUNCEMENT",
    seen: true,
    blog: { blogId: "b112" },
    actor: { userId: "system" },
    recipient: { userId: "u012" },
    createdAt: "2025-11-01T16:00:00Z",
  },
];

export const applications: Application[] = [
  {
    applicationId: "a1",
    email: "john.doe@example.com",
    resumeUrl: "https://resumes.com/johndoe.pdf",
    status: "Pending",
    user: { userId: "u101", fullName: "John Doe" },
    recruiterName: "Alice Nguyen",
    job: { jobId: "j201", title: "Frontend Developer" },
    history: [
      {
        status: "Submitted",
        updatedAt: new Date("2025-10-01T09:00:00Z"),
        updatedBy: { id: "r001", email: "alice.hr@example.com" },
      },
    ],
    createdAt: "2025-10-01T08:55:00Z",
    createdBy: "u101",
    isDeleted: false,
  },
  {
    applicationId: "a2",
    email: "sara.lee@example.com",
    resumeUrl: "https://resumes.com/saralee.pdf",
    status: "Interview Scheduled",
    user: { userId: "u102", fullName: "Sara Lee" },
    recruiterName: "Bob Tran",
    job: { jobId: "j202", title: "Backend Engineer" },
    history: [
      {
        status: "Pending",
        updatedAt: new Date("2025-09-28T14:00:00Z"),
        updatedBy: { id: "r002", email: "bob.hr@example.com" },
      },
      {
        status: "Interview Scheduled",
        updatedAt: new Date("2025-10-02T10:30:00Z"),
        updatedBy: { id: "r002", email: "bob.hr@example.com" },
      },
    ],
    createdAt: "2025-09-28T13:50:00Z",
    createdBy: "u102",
    isDeleted: false,
  },
  {
    applicationId: "a3",
    email: "kevin.nguyen@example.com",
    resumeUrl: "https://resumes.com/kevinnguyen.pdf",
    status: "Rejected",
    user: { userId: "u103", fullName: "Kevin Nguyen" },
    recruiterName: "Linh Pham",
    job: { jobId: "j203", title: "UI/UX Designer" },
    history: [
      {
        status: "Pending",
        updatedAt: new Date("2025-09-20T09:00:00Z"),
        updatedBy: { id: "r003", email: "linh.hr@example.com" },
      },
      {
        status: "Rejected",
        updatedAt: new Date("2025-09-22T15:00:00Z"),
        updatedBy: { id: "r003", email: "linh.hr@example.com" },
      },
    ],
    createdAt: "2025-09-20T08:45:00Z",
    createdBy: "u103",
    isDeleted: false,
  },
  {
    applicationId: "a4",
    email: "amy.tran@example.com",
    resumeUrl: "https://resumes.com/amytran.pdf",
    status: "Offer Sent",
    user: { userId: "u104", fullName: "Amy Tran" },
    recruiterName: "David Hoang",
    job: { jobId: "j204", title: "Data Analyst" },
    history: [
      {
        status: "Interview Completed",
        updatedAt: new Date("2025-10-01T11:00:00Z"),
        updatedBy: { id: "r004", email: "david.hr@example.com" },
      },
      {
        status: "Offer Sent",
        updatedAt: new Date("2025-10-03T09:00:00Z"),
        updatedBy: { id: "r004", email: "david.hr@example.com" },
      },
    ],
    createdAt: "2025-09-25T12:00:00Z",
    createdBy: "u104",
    isDeleted: false,
  },
  {
    applicationId: "a5",
    email: "michael.vo@example.com",
    resumeUrl: "https://resumes.com/michaelvo.pdf",
    status: "Accepted",
    user: { userId: "u105", fullName: "Michael Vo" },
    recruiterName: "Quynh Le",
    job: { jobId: "j205", title: "DevOps Engineer" },
    history: [
      {
        status: "Offer Sent",
        updatedAt: new Date("2025-09-30T10:00:00Z"),
        updatedBy: { id: "r005", email: "quynh.hr@example.com" },
      },
      {
        status: "Accepted",
        updatedAt: new Date("2025-10-02T14:00:00Z"),
        updatedBy: { id: "r005", email: "quynh.hr@example.com" },
      },
    ],
    createdAt: "2025-09-28T09:30:00Z",
    createdBy: "u105",
    isDeleted: false,
  },
  {
    applicationId: "a6",
    email: "tom.ho@example.com",
    resumeUrl: "https://resumes.com/tomho.pdf",
    status: "Pending",
    user: "u106",
    recruiterName: "Alice Nguyen",
    job: "j206",
    createdAt: "2025-10-04T08:00:00Z",
    createdBy: "u106",
    isDeleted: false,
  },
  {
    applicationId: "a7",
    email: "lucy.pham@example.com",
    resumeUrl: "https://resumes.com/lucypham.pdf",
    status: "Interview Completed",
    user: { userId: "u107", fullName: "Lucy Pham" },
    recruiterName: "Huy Tran",
    job: { jobId: "j207", title: "Product Manager" },
    createdAt: "2025-10-01T08:45:00Z",
    createdBy: "u107",
    isDeleted: false,
  },
  {
    applicationId: "a8",
    email: "danny.ngo@example.com",
    resumeUrl: "https://resumes.com/dannyngo.pdf",
    status: "Pending Review",
    user: { userId: "u108", fullName: "Danny Ngo" },
    recruiterName: "Alice Nguyen",
    job: { jobId: "j208", title: "QA Engineer" },
    createdAt: "2025-10-05T13:00:00Z",
    createdBy: "u108",
    isDeleted: false,
  },
  {
    applicationId: "a9",
    email: "emily.nguyen@example.com",
    resumeUrl: "https://resumes.com/emilynguyen.pdf",
    status: "Withdrawn",
    user: { userId: "u109", fullName: "Emily Nguyen" },
    recruiterName: "Bob Tran",
    job: { jobId: "j209", title: "Business Analyst" },
    history: [
      {
        status: "Pending",
        updatedAt: new Date("2025-09-29T09:00:00Z"),
        updatedBy: { id: "r002", email: "bob.hr@example.com" },
      },
      {
        status: "Withdrawn",
        updatedAt: new Date("2025-10-01T09:00:00Z"),
        updatedBy: { id: "u109", email: "emily.nguyen@example.com" },
      },
    ],
    createdAt: "2025-09-29T08:30:00Z",
    createdBy: "u109",
    isDeleted: false,
  },
  {
    applicationId: "a10",
    email: "tony.le@example.com",
    resumeUrl: "https://resumes.com/tonyle.pdf",
    status: "Deleted",
    user: { userId: "u110", fullName: "Tony Le" },
    recruiterName: "David Hoang",
    job: { jobId: "j210", title: "Software Architect" },
    createdAt: "2025-09-15T09:00:00Z",
    createdBy: "u110",
    isDeleted: true,
    deletedAt: true,
  },
];

export const users: User[] = [
  {
    userId: "u101",
    fullName: "John Doe",
    address: "123 Nguyen Trai, Ha Noi",
    contact: { email: "john.doe@example.com", phone: "+84 912345678" },
    dob: new Date("1998-05-20"),
    gender: "Male",
    password: "hashed_password_1",
    username: "john_doe",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=80",
    enabled: true,
    role: { roleId: "r1", name: "Applicant" },
    savedJob: { jobId: "j201", title: "Frontend Developer" },
    followedRecruiter: { userId: "u201", fullName: "Alice Nguyen" },
    createdAt: "2025-10-01T09:00:00Z",
    createdBy: "system",
    isDeleted: false,
  },
  {
    userId: "u102",
    fullName: "Sara Lee",
    address: "45 Le Loi, Da Nang",
    contact: { email: "sara.lee@example.com", phone: "+84 934567890" },
    dob: new Date("1997-10-05"),
    gender: "Female",
    password: "hashed_password_2",
    username: "sara_lee",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=80",
    enabled: true,
    role: { roleId: "r2", name: "Applicant" },
    savedJob: { jobId: "j202", title: "Backend Engineer" },
    followedRecruiter: { userId: "u203", fullName: "David Hoang" },
    createdAt: "2025-09-28T13:30:00Z",
    createdBy: "system",
    isDeleted: false,
  },
  {
    userId: "u201",
    fullName: "Alice Nguyen",
    address: "10 Nguyen Hue, Ho Chi Minh City",
    contact: { email: "alice.hr@example.com", phone: "+84 965432100" },
    dob: new Date("1988-11-02"),
    gender: "Female",
    password: "hashed_password_3",
    username: "alice_hr",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=80",
    enabled: true,
    role: { roleId: "r3", name: "Recruiter" },
    createdAt: "2025-09-15T08:00:00Z",
    createdBy: "admin",
    isDeleted: false,
  },
  {
    userId: "u202",
    fullName: "David Hoang",
    address: "56 Tran Phu, Nha Trang",
    contact: { email: "david.hr@example.com", phone: "+84 933221177" },
    dob: new Date("1985-03-10"),
    gender: "Male",
    password: "hashed_password_4",
    username: "david_hoang",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=80",
    enabled: true,
    role: { roleId: "r3", name: "Recruiter" },
    createdAt: "2025-09-12T10:15:00Z",
    createdBy: "admin",
    isDeleted: false,
  },
  {
    userId: "u001",
    fullName: "System Admin",
    contact: { email: "admin@example.com", phone: "+84 900000000" },
    password: "super_admin_pass",
    username: "admin",
    avatar:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=80",
    enabled: true,
    role: { roleId: "r0", name: "Admin" },
    createdAt: "2025-09-01T00:00:00Z",
    createdBy: "system",
    isDeleted: false,
  },
];
